#path to eggnog db
eggnog_db_path:
    cluster_path: /project/balan/bin/eggnog-mapper-2.1.3/data/
    local_path: eggnog_database/
MWM_mushroom: #Please put {species} here the same way it will be called in wildcard
    genomeSize: 28    #in million bp
    others: something_related
